version: '2'
services:

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: salad_server:1

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile.worker
    image: salad_worker:1

  worker-monit:
    build:
      context: ./worker
      dockerfile: Dockerfile.monit
    image: salad_monit:1

