FROM rodrigoibka/backend:1.0

ENV DEBIAN_FRONTEND noninteractive
ENV LC_ALL C.UTF-8
ENV LANG C.UTF-8

# -- Install Application into container:
RUN mkdir /app

WORKDIR /app

COPY ./ /app/

# -- Install dependencies:
RUN pipenv install --deploy --system

EXPOSE 5672

ENTRYPOINT ["celery", "-E", "-A", "worker:app","worker", "--loglevel=INFO", "--autoscale=10,5"]
